version: "3.8"

services:
  app:
    build:
      context: ./ongil
      dockerfile: Dockerfile
    image: ghcr.io/rabent/ongil-backend:latest
    env_file:
      - .env
    command: tail -f /dev/null
