version: "3.8"

services:
  app:
    build:
      context: ./ongil
      dockerfile: Dockerfile
    image: registry.lab.ssafy.com/s13-final/S13P31A305/ongil:latest
    env_file:
      - .env
    command: tail -f /dev/null
